<script setup lang="ts">
import { onMounted, ref } from 'vue'
import AdminLayout from '../layouts/AdminLayout.vue'
import { getBotConfig, saveBotConfig, startBot, stopBot, type BotConfig } from '../api/admin'
const form = ref<BotConfig>({ bot_token:'', webhook_port:'8080', webhook_path:'/telegram/webhook', webhook_secret:'', commands_json:'[{"command":"start","description":"开始使用"}]', keyboard_json:'[]', welcome_html:'<b>欢迎使用 Telegram Bot</b>', bot_running:false })
const toast = ref(''); const loading = ref(false)
async function load(){ form.value = await getBotConfig() }
async function save(){ loading.value=true; try{ form.value = await saveBotConfig(form.value); toast.value='配置已保存' } finally{ loading.value=false } }
async function toggle(){ loading.value=true; try{ form.value.bot_running ? await stopBot() : await startBot(); await load(); toast.value = form.value.bot_running ? 'Bot 已启动' : 'Bot 已停止' } finally{ loading.value=false } }
onMounted(load)
</script>
<template><AdminLayout><div class="mb-8 flex items-center justify-between"><div><h1 class="text-3xl font-black">Telegram Bot 管理</h1><p class="text-slate-500">保存 token、webhook、指令、键盘与欢迎语后再启动 Bot。</p></div><span class="badge">{{ form.bot_running ? '实时运行' : '等待启动' }}</span></div><div v-if="toast" class="mb-4 rounded-2xl bg-emerald-50 p-4 text-emerald-700">{{ toast }}</div><div class="grid gap-6 lg:grid-cols-3"><form class="card space-y-4 p-6 lg:col-span-2" @submit.prevent="save"><div class="grid gap-4 md:grid-cols-2"><div><label class="label">Bot Token</label><input v-model="form.bot_token" class="input" placeholder="123456:ABC"></div><div><label class="label">Webhook SECRET</label><input v-model="form.webhook_secret" class="input" placeholder="高强度密钥"></div><div><label class="label">Webhook 端口</label><input v-model="form.webhook_port" class="input"></div><div><label class="label">Webhook 路径</label><input v-model="form.webhook_path" class="input"></div></div><label class="label">Commands 指令 JSON</label><textarea v-model="form.commands_json" class="input h-28 font-mono"></textarea><label class="label">内联回复键盘 JSON（三个一组）</label><textarea v-model="form.keyboard_json" class="input h-28 font-mono"></textarea><label class="label">/start 欢迎消息 HTML</label><textarea v-model="form.welcome_html" class="input h-40"></textarea><div class="flex gap-3"><button class="btn-primary" :disabled="loading">保存配置</button><button type="button" class="btn bg-slate-900 text-white" @click="toggle" :disabled="loading">{{ form.bot_running ? '停止 Bot' : '确认启动 Bot' }}</button></div></form><aside class="card p-6"><h2 class="mb-4 text-xl font-bold">实时监控</h2><div class="space-y-4"><div class="rounded-3xl bg-slate-50 p-4"><p class="text-slate-500">Webhook</p><b>{{ form.webhook_path }}</b></div><div class="rounded-3xl bg-slate-50 p-4"><p class="text-slate-500">运行状态</p><b :class="form.bot_running?'text-emerald-600':'text-slate-400'">{{ form.bot_running ? '在线' : '离线' }}</b></div><div class="rounded-3xl bg-blue-50 p-4 text-blue-700">配置变更会通过后端保存到 PostgreSQL，并在启动时注入全局 Bot 管理器。</div></div></aside></div></AdminLayout></template>
